### ISSUE TITLE
`:false` and `:null` aren't encoded as `false` and `null`.

### ISSUE THREAD

**Issue by joostkremers** [zkry/yaml.el#10]
Another round-trip issue: if my input yaml file contains `false` or `null`, parsing the file yields the keywords `:false` and `:null`. When encoded back to yaml, these end up as the strings `:false` and `:null`.

I can understand that round-tripping is impossible if you specify `:false-object` or `:null-object` during parsing (though I admit it would be nice to have something like `:nil-object` in `yaml-encode`), but I think it would be nice if `:false` and `:null` are handled.

**Comment by zkry** [comment]
Thanks for bringing these two issues up! I agree, :false and :null should definitely be handled.

**Comment by zkry** [comment]
This problem and the encoding of vectors should now be fixed in the v0.2.1 release. Thanks again for bringing this up!

**Comment by joostkremers** [comment]
Great, thanks!
