### ISSUE TITLE
Recent Emacs's escape character handing improment leads to an error when loading yaml.el

### ISSUE THREAD

**Issue by VitalyAnkh** [zkry/yaml.el#45]
With this commit: https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=b8e7061232f9a5b06af70031dcc4b48c6575a364, there is an error when loading yaml.el:
```
  x There was an unexpected runtime error
    Message: Invalid escape character syntax
    Backtrace:
      (read #<buffer  *load*-16599>)
      (load-with-code-conversion "/home/vitalyr/.config/.emacs.d/.local/straight/build-30.0.50/yaml/y...
      (require yaml)
```

**Comment by zkry** [comment]
Thanks for opening this issue! I think I found the issue. I was escaping the character `x` by accident. I'll get a fix in soon.

**Comment by zkry** [comment]
Should be good to go in the latest release
