### ISSUE TITLE
`yaml-encode` inserts unnecessary newline at the beginning of the returned value

### ISSUE THREAD

**Issue by rodrigo-morales-1** [zkry/yaml.el#48]
`yaml-encode` always insert a newline at the beginning of the output. As far as I'm concerned, the YAML specification doesn't state that a YAML object should start with a newline, so this newline is not mandatory.

<a id="org5e41111"></a>

# Example no. 1

```elisp
(yaml-encode '((a . 10)))
```

    "
    a: 10"

In Python:

```text
>>> import yaml
>>> yaml.dump({'a': 10})
'a: 10\n'
>>>
```

<a id="orga80287f"></a>

# Example no. 2

```elisp
(yaml-encode '(((a . 10))
               ((a . 20))))
```

    "
    - a: 10
    - a: 20"

In Python:

```text
>>> import yaml
yaml.dump([{'a': 10}, {'a': 20}])
'- a: 10\n- a: 20\n'
>>>
```

**Comment by zkry** [comment]
Hi! Thanks for this issue. Yeah your right, it would be better without this leading new-line. I'll include a change to remove it 👍

**Comment by zkry** [comment]
Ok, should be good to go in the next release.
