### ISSUE TITLE
Incorrect octal and hexadecimal scalar parsing

### ISSUE THREAD

**Issue by nagy** [zkry/yaml.el#54]
Example:

```elisp
(yaml-parse-string "foo: 0x200" :object-type 'alist)
;; => ((foo . 0))

(yaml-parse-string "foo: 0o1000" :object-type 'alist)
;; => ((foo . 0))
```

The reason for that is this code:

```elisp
((string-match "^0o[0-7]+$" scalar)
 (string-to-number scalar 8))
((string-match "^0x[0-9a-fA-F]+$" scalar)
 (string-to-number scalar 16))
```

Here, `scalar`, still has the prefix attached and `string-to-number` cannot handle that. The prefix needs to be stripped off first, or a substring of `scalar` needs to be passed.

**Comment by zkry** [comment]
Thanks for the bug report and locating the problem! I should get the fix for this out soon.
