### ISSUE TITLE
Version metadata should be kept in sync with released versions

### ISSUE THREAD

**Issue by progfolio** [zkry/yaml.el#55]
yaml.el declares a Version of : 0.5.1, but the latest release is 0.5.4.

v0.5.4 [Latest](https://github.com/zkry/yaml.el/releases/latest)

https://github.com/zkry/yaml.el/blob/fe08b8f5307af1e7b876ece64b7303213f04b63c/yaml.el#L6

I'm adding package version checks in Elpaca (and possible straight.el), so it would be nice to keep this info in sync.

**Comment by zkry** [comment]
Thanks for this reminder! Should be good now.
