### ISSUE TITLE
Writing yaml?

### ISSUE THREAD

**Issue by joostkremers** [zkry/yaml.el#6]
Hi, this is great, a yaml parser in Elisp could be very useful for me, so I'll be checking it out soon. I was wondering if you had any plans to add a yaml writer?

**Comment by zkry** [comment]
Hey, definitely! This is top on my list of things I want to include.

**Comment by joostkremers** [comment]
Great! I'll keep an eye out for updates.

**Comment by zkry** [comment]
This feature should exist now in the latest release!
https://github.com/zkry/yaml.el/releases/tag/v0.2.0

**Comment by joostkremers** [comment]
Great, thanks for the heads up!
